import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { getCoverData } from "@/lib/getPostsData";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ sortedAllPosts }: { sortedAllPosts: any }) {
    return (
        <>
            <Head>
                <title>wlaterDesign</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main>
                <div className="grid">
                    {sortedAllPosts.map((posts: any) => {
                        return (
                            <Link href={`/${posts.id}`} key={posts.id}>
                                <div className="grid-item">
                                    <img
                                        className="item-thumbnail"
                                        src={posts.thumbnail}
                                        alt="cover"
                                    />
                                    <h2>{posts.title}</h2>
                                </div>
                            </Link>
                        );
                    })}
                </div>
            </main>
            <style jsx>
                {`
                    .grid {
                        max-width: 100%;
                        display: grid;
                        grid-template-columns: 1fr 1fr;
                        grid-gap: 2rem;
                        padding: 2rem;
                    }
                    .grid-item {
                        width: 100%;
                    }
                    .grid-item img {
                        width: 100%;
                        height: 72rem;
                        object-fit: cover;
                    }
                    h2 {
                        font-size: 1.8rem;
                        font-weight: 400;
                    }
                    .item-thumbnail {
                        margin-bottom: 0.8rem;
                    }

                    @media all and (min-width: 320px) and (max-width: 390px) {
                        .grid {
                            grid-template-columns: 1fr;
                        }
                        .grid-item img {
                     
                        height: 24rem;
                     
                    }                    
                `}
            </style>
        </>
    );
}

export async function getStaticProps() {
    const coverData = await getCoverData();

    const sortedAllPosts = coverData.sort((a: any, b: any) => {
        if (a.date < b.date) {
            return 1;
        } else {
            return -1;
        }
    });

    return {
        props: { sortedAllPosts },
    };
}
